export default {
    NEW_POST_ADDED: 'NEW_POST_ADDED',
    NEW_USER_ADDED: 'NEW_USER_ADDED',
    LOGGED_IN: 'LOGGED_IN',
    COMMENT_ADDED: 'COMMENT_ADDED',
    LIKE_ADDED: 'LIKE_ADDED',
    REPLY_THREAD_TOGGLED: 'REPLY_THREAD_TOGGLED'
}
